{% set name = "flake8" %}
{% set version = "7.4.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/PyCQA/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 10697bfa70871fec59b58c59158254246ba0a13c6fee50bd3a6858329d2a93de

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  entry_points:
    - flake8 = flake8.main.cli:main

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - mccabe >=0.7.0,<0.8.0
    - pycodestyle >=2.15.0,<2.16.0
    - pyflakes >=4.0.0,<4.1.0

test:
  source_files:
    - tests
    - bin/gen-pycodestyle-plugin
    - docs/source/user/error-codes.rst
  imports:
    - flake8
    - flake8.api
    - flake8.formatting
    - flake8.main
    - flake8.options
    - flake8.plugins
  commands:
    - pip check
    - flake8 --help
    - pytest -vv tests
  requires:
    - pip
    - pytest !=3.0.5,!=5.2.3

about:
  home: https://flake8.pycqa.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    Flake8 runs all the tools by launching the single flake8 command. It displays the warnings in a per-file, merged output.
  summary: Your Tool For Style Guide Enforcement
  doc_url: https://flake8.pycqa.org/
  dev_url: https://github.com/PyCQA/flake8

extra:
  recipe-maintainers:
    - sigmavirus24
    - croth1
    - dopplershift
    - goanpeca
    - aydinhan
