{% set version = "6.1.0" %}

package:
  name: flake8
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/flake8/flake8-{{ version }}.tar.gz
  sha256: d5b3857f07c030bdb5bf41c7f53799571d75c4491748a3adcd47de929e34cd23

build:
  number: 0
  skip: True # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  entry_points:
    - flake8 = flake8.main.cli:main

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools >=30.0.0
  run:
    - python
    - mccabe >=0.7.0,<0.8.0
    - pycodestyle >=2.11.0,<2.12.0
    - pyflakes >=3.1.0,<3.2.0

test:
  imports:
    - flake8
  requires:
    - pip
  source_files:
    - src/flake8
    - tests/integration
    - tests/unit
    - setup.py

  commands:
    - flake8 --ignore=D203,W503,E203 src/flake8 tests/integration tests/unit setup.py  # [unix]
    - flake8 --ignore=D203,W503,E203 src\\flake8 tests\\integration tests\\unit setup.py  # [win]
    - pip check

about:
  home: https://flake8.pycqa.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    Flake8 runs all the tools by launching the single flake8 command. It displays the warnings in a per-file, merged output.
  summary: Your Tool For Style Guide Enforcement
  doc_url: https://flake8.pycqa.org/
  dev_url: https://github.com/PyCQA/flake8

extra:
  recipe-maintainers:
    - sigmavirus24
    - croth1
    - dopplershift
    - goanpeca
    - aydinhan
