{% set version = "7.1.1" %}

package:
  name: flake8
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/flake8/flake8-{{ version }}.tar.gz
  sha256: 049d058491e228e03e67b390f311bbf88fce2dbaa8fa673e7aea87b7198b8d38

build:
  number: 0
  skip: True # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  entry_points:
    - flake8 = flake8.main.cli:main

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - mccabe >=0.7.0,<0.8.0
    - pycodestyle >=2.12.0,<2.13.0
    - pyflakes >=3.2.0,<3.3.0

test:
  imports:
    - flake8
    - flake8.api
    - flake8.formatting
    - flake8.main
    - flake8.options
    - flake8.plugins
  requires:
    - pip
  commands:
    # Cannot run pytest since source does not come with tests.
    - pip check

about:
  home: https://flake8.pycqa.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    Flake8 runs all the tools by launching the single flake8 command. It displays the warnings in a per-file, merged output.
  summary: Your Tool For Style Guide Enforcement
  doc_url: https://flake8.pycqa.org/
  dev_url: https://github.com/PyCQA/flake8

extra:
  recipe-maintainers:
    - sigmavirus24
    - croth1
    - dopplershift
    - goanpeca
    - aydinhan
