{% set name = "flake8" %}
{% set version = "7.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/PyCQA/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 71a7d2ec4166f83c6fc66e6465a45c49b4565ee29b69f27b335366ce101d8c2b

build:
  number: 0
  skip: True # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  entry_points:
    - flake8 = flake8.main.cli:main

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - mccabe >=0.7.0,<0.8.0
    - pycodestyle >=2.14.0,<2.15.0
    - pyflakes >=3.4.0,<3.5.0

test:
  source_files:
    - tests
    - bin/gen-pycodestyle-plugin
  imports:
    - flake8
    - flake8.api
    - flake8.formatting
    - flake8.main
    - flake8.options
    - flake8.plugins
  commands:
    - pip check
    - flake8 --help
    - pytest -v tests
  requires:
    - pip
    - pytest !=3.0.5,!=5.2.3

about:
  home: https://flake8.pycqa.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    Flake8 runs all the tools by launching the single flake8 command. It displays the warnings in a per-file, merged output.
  summary: Your Tool For Style Guide Enforcement
  doc_url: https://flake8.pycqa.org/
  dev_url: https://github.com/PyCQA/flake8

extra:
  recipe-maintainers:
    - sigmavirus24
    - croth1
    - dopplershift
    - goanpeca
    - aydinhan
