{% set version = "6.0.0" %}

package:
  name: flake8
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/flake8/flake8-{{ version }}.tar.gz
  sha256: c61007e76655af75e6785a931f452915b371dc48f56efd765247c8fe68f2b181

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - flake8 = flake8.main.cli:main

requirements:
  host:
    - python >=3.8.1
    - pip
    - wheel
    - setuptools >=30.0.0
  run:
    - python >=3.8.1
    - mccabe >=0.7.0,<0.8.0
    - pycodestyle >=2.10.0,<2.11.0
    - pyflakes >=3.0.0,<3.1.0

test:
  imports:
    - flake8
  requires:
    - pip
  source_files:
    - src/flake8
    - tests/integration
    - tests/unit
    - setup.py

  commands:
    - flake8 --ignore=D203,W503,E203 src/flake8 tests/integration tests/unit setup.py  # [unix]
    - flake8 --ignore=D203,W503,E203 src\\flake8 tests\\integration tests\\unit setup.py  # [win]
    # 2022/03/24: the pip test does not work at this time
    # Enable it when mccabe bump a verion number
    #- pip check

about:
  home: http://flake8.pycqa.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    Flake8 runs all the tools by launching the single flake8 command. It displays the warnings in a per-file, merged output.
  summary: Your Tool For Style Guide Enforcement
  doc_url: https://flake8.pycqa.org/
  dev_url: https://gitlab.com/pycqa/flake8

extra:
  recipe-maintainers:
    - sigmavirus24
    - croth1
    - dopplershift
    - goanpeca
    - aydinhan
