{% set version = "4.0.1" %}

package:
  name: flake8
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/flake8/flake8-{{ version }}.tar.gz
  sha256: 806e034dda44114815e23c16ef92f95c91e4c71100ff52813adf7132a6ad870d

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - flake8 = flake8.main.cli:main

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools >=30.0.0
  run:
    - python
    # mccabe 0.7.0 is a noarch python package now and it hasn't broken changes for flake8
    - mccabe >=0.6.0,<0.7.0
    - pycodestyle >=2.8.0,<2.9.0
    - pyflakes >=2.4.0,<2.5.0
    - importlib-metadata
test:
  imports:
    - flake8
  requires:
    - pip
  source_files:
    - src/flake8
    - tests/integration
    - tests/unit
    - setup.py

  commands:
    - flake8 --ignore=D203,W503,E203 src/flake8 tests/integration tests/unit setup.py  # [unix]
    - flake8 --ignore=D203,W503,E203 src\\flake8 tests\\integration tests\\unit setup.py  # [win]
    - pip check

about:
  home: https://flake8.pycqa.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  license_url: https://github.com/PyCQA/flake8/blob/main/LICENSE
  summary: Your Tool For Style Guide Enforcement
  description: |
    flake8 is a python tool that glues together pycodestyle, pyflakes,
    mccabe, and third-party plugins to check the style and quality of
    some python code.
  doc_url: https://flake8.pycqa.org/
  doc_source_url: https://github.com/PyCQA/flake8/blob/main/docs/source/index.rst
  dev_url: https://gitlab.com/pycqa/flake8

extra:
  recipe-maintainers:
    - sigmavirus24
    - croth1
    - dopplershift
    - goanpeca
    - aydinhan
