travis:
  secure:
    BINSTAR_TOKEN: PGb/fz8raHRpcTixnBHzEJwhe5Zlg2YYWtfPWDHVULVvyqLn+hQphYkQQO7qCsQLqPWdlDbM0yIP1ONb4tNwpaPbrovDQ4NpEqoTLCLI3ZxgT0vltYw1tEgNWR55/aVvSvYVP5nSQ6L4NLzSOaLCHAP2u6mWNMl4wjYiaRqqTKK129CnUxRemylFhX2QHGtrFdtWJqk5EmUK8XKLn0so8FjNHw7BHVikcLBpW5djIt6Zc9Jn/6nZtH3nlnMbV+FeNk2Ww8OyjsPrFsd6wk5Gg7lXK97aKMMVr21PJOjApeyQlxmf9sAwjB5xsOlN8B3xzfBjSK0DwNqyEPRTQYOCV/grvTgB85LjW13l78CVWQjoXVlTnMJebUXOOw9wjoL3h1VJj8esEssHWDYUE0gakYFBaH9nDL2elLZEa5/mDKcEUYnFDAolDwM62WVgoorg1GTHzKJDvbLCaYbKFE+OK3RIMg98zQl0YSV2MLASFARhSSuu+ltR32mfkq/P1XHzzBxxuzoJ3UMNGnk1/wj9egxpP93+aQa3P2EEi8LnVhnlDBT6AMX55PjXWPJaosGMOC0W20dGBi4j0l3nDpMeuC1h6Q67H0uPlU8IVjMZECVeZVnfAWwejQWlKscFm+YZpbXVqoRsQBSJo3UOnzi7AQvIhwV2lJNclygc9yzYTJA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
