travis:
  secure:
    BINSTAR_TOKEN: tdHfjrBmAqfYH+RYVatiYQTBXqOukO7/GhmDK8KZqA+ZNk208CJiOv32oULTQzJp4IL7bF8Yb8ifXd110fO+MXje0HQj48l7qWOEPz7Vf2tk4Z0U9rng6T2WFLLXwvWjD1hfqPWwUHaGllHJXlvL47KkwXICc0p4l0ZAD1QRCwQhyPtTaEXwTUwuHR5zZjXxKFFSWKe/BrK//c072P6YRQc4IxeL/iRzl+HRB7c9OMnUFfuj2Z+gphsjVWtlU3GmcZhy4wTfGJu9huRF5ZNsQwX+SqDZ/1PGw4+nfYY1onplvF+pdHrgI0vXolDsqq+m7CRpKUetNSS2ufNDOrvX2FO0iTM0T7GKQf9Smz12FGoV0Z7vfKk02vrlQLhf5hcQORtICP6jXZf+B7eP/hqHeFu6LZdlJ8GM65wIZCBunI+E6l5SfFIyVMnyJENCf/ae/8GNx05DlAyJ5TGNC37ANs1GRBFYUCJsO9Z7kXZu5V8/Nfd0lCChWrLB2KfImV2jdK68kfLUVJUjPrPQhjnQeqeX2OBDLQDNLcyeXjMoO36/sTJ+ULciQMwHyHmn1e2BXsKyhQTbsez34rdlImrTDV5LpoAzgZp5koAlSeQtPZ90i6j/RT6Hdwc67Nswqh+LZHWj4MHPY0LrKCwioF3ilBdoE95gHk1W43YvAyo46Hw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
